# Generated by Django 5.0.12 on 2025-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_max_questions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examincorrectwordquestion',
            name='selected_letter_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='выбранный номер неправильной буквы'),
        ),
        migrations.AlterField(
            model_name='examoptionsquestion',
            name='selected_option1_is_true',
            field=models.BooleanField(blank=True, null=True, verbose_name='первый вариант ответа верный'),
        ),
        migrations.AlterField(
            model_name='examoptionsquestion',
            name='selected_option2_is_true',
            field=models.BooleanField(blank=True, null=True, verbose_name='второй вариант ответа верный'),
        ),
        migrations.AlterField(
            model_name='examoptionsquestion',
            name='selected_option3_is_true',
            field=models.BooleanField(blank=True, null=True, verbose_name='третий вариант ответа верный'),
        ),
    ]
