# Generated by Django 4.2 on 2025-02-01 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название задачи')),
                ('description', models.TextField(verbose_name='описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='дата начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='экзаменуемый')),
            ],
            options={
                'verbose_name': 'испытание',
                'verbose_name_plural': 'испытания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OptionsQuestionBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=255, verbose_name='вопрос')),
                ('option1', models.CharField(default='', max_length=255, verbose_name='первый вариант ответа')),
                ('option1_is_true', models.BooleanField(verbose_name='первый вариант ответа верный')),
                ('option2', models.CharField(default='', max_length=255, verbose_name='второй вариант ответа')),
                ('option2_is_true', models.BooleanField(verbose_name='второй вариант ответа верный')),
                ('option3', models.CharField(default='', max_length=255, verbose_name='третий вариант ответа')),
                ('option3_is_true', models.BooleanField(verbose_name='третий вариант ответа верный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'вопрос с вариантами ответа',
                'verbose_name_plural': 'вопросы с вариантами ответа',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IncorrectWordQuestionBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_word', models.CharField(max_length=255, verbose_name='правильная форма слова')),
                ('incorrect_word', models.CharField(max_length=255, verbose_name='форма слова с ошибкой')),
                ('incorrect_letter_index', models.IntegerField(verbose_name='номер неправильной буквы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'вопрос с неправильной буквой в слове',
                'verbose_name_plural': 'вопросы с неправильной буквой в слове',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ExamOptionsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=255, verbose_name='вопрос')),
                ('option1', models.CharField(default='', max_length=255, verbose_name='первый вариант ответа')),
                ('option1_is_true', models.BooleanField(verbose_name='первый вариант ответа верный')),
                ('option2', models.CharField(default='', max_length=255, verbose_name='второй вариант ответа')),
                ('option2_is_true', models.BooleanField(verbose_name='второй вариант ответа верный')),
                ('option3', models.CharField(default='', max_length=255, verbose_name='третий вариант ответа')),
                ('option3_is_true', models.BooleanField(verbose_name='третий вариант ответа верный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения')),
                ('selected_option1_is_true', models.BooleanField(verbose_name='первый вариант ответа верный')),
                ('selected_option2_is_true', models.BooleanField(verbose_name='второй вариант ответа верный')),
                ('selected_option3_is_true', models.BooleanField(verbose_name='третий вариант ответа верный')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.userexam', verbose_name='испытание')),
            ],
            options={
                'verbose_name': 'вопрос в испытании c выбором варианта ответа',
                'verbose_name_plural': 'вопросы в испытании c выбором варианта ответа',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ExamIncorrectWordQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_word', models.CharField(max_length=255, verbose_name='правильная форма слова')),
                ('incorrect_word', models.CharField(max_length=255, verbose_name='форма слова с ошибкой')),
                ('incorrect_letter_index', models.IntegerField(verbose_name='номер неправильной буквы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения')),
                ('selected_letter_index', models.IntegerField(verbose_name='выбранный номер неправильной буквы')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.userexam', verbose_name='испытание')),
            ],
            options={
                'verbose_name': 'вопрос в испытании c неправильной буквой',
                'verbose_name_plural': 'вопросы в испытаниях c неправильной буквой',
                'ordering': ('id',),
            },
        ),
    ]
