# Generated by Django 4.2 on 2025-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_questions_count',
            field=models.PositiveIntegerField(default=1, verbose_name='максимальное количество вопросов в испытании'),
        ),
    ]
